module.exports = {
  preset: 'react-native',
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|expo|@expo|@react-native/js-polyfills|@testing-library|react-native-url-polyfill|@supabase|@sentry|victory-native|@react-navigation|react-native-screens|react-native-safe-area-context|react-native-gesture-handler|react-native-svg|@react-native-async-storage|@react-native-voice)/)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  setupFiles: ['<rootDir>/jest.setup.js'],
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect', '<rootDir>/src/setupTests.ts'],
  testEnvironment: 'node',
  testPathIgnorePatterns: [
    'src/hooks/__tests__/useVoiceRecording.test.ts',
    'src/hooks/__tests__/useRestTimer.test.ts',
    'src/services/__tests__/voiceService.test.ts',
    'src/data/__tests__/exerciseDictionary.test.ts',
    'src/components/__tests__/ExerciseChart.test.tsx',
    'src/components/__tests__/ProgressCircle.test.tsx',
    'src/lib/__tests__/authService.test.ts',
    'src/llm/__tests__/openai.test.ts',
    'src/llm/__tests__/formatMemoPrompt.test.ts',
    'src/llm/__tests__/formatExercisePrompt.test.ts',
    'src/llm/__tests__/index.test.ts',
    './App.test.tsx',
  ],
  moduleNameMapper: {
    '^@react-native/js-polyfills/error-guard$': 'identity-obj-proxy',
    '^react-native-url-polyfill/auto$': 'identity-obj-proxy',
    '^@sentry/react-native$': '<rootDir>/src/__mocks__/@sentry/react-native.js',
    '^expo-notifications$': '<rootDir>/src/__mocks__/expo-notifications.js',
    '^expo-av$': '<rootDir>/src/__mocks__/expo-av.js',
  },
};
